FROM resin/%%RESIN_ARCH%%-alpine-node

RUN npm install --global localtunnel

RUN JOBS=MAX npm install --production --unsafe-perm && npm cache clean && rm -rf /tmp/*

ADD . /app

WORKDIR /app

CMD ["sh", "/start.sh"]
