FROM resin/%%RESIN_ARCH%%-alpine:latest

RUN apk update && apk add nodejs bash py-pip && \
  npm install --global localtunnel && \
  rm -rf /var/cache/apk/* && \
  pip install --upgrade pip && \
  pip install flask

ADD . /app

WORKDIR /app

CMD ["sh", "start.sh"]
